localizedStrings["en"] = new Array();

localizedStrings["en"]["Loading... Please wait."] = "Loading... Please wait. <img src=\"Images/loader.gif\" class=\"loader\" width=\"16\" height=\"16\" valign=\"middle\" />";
localizedStrings["en"]["needs_config"] = "Configuration needed...<br/>Please enter your Vid&eacute;otron User Key<br/>in the widget's preferences.";
localizedStrings["en"]["Oh Noes! There's been an error."] = "Oh Noes! There's been an error.";
localizedStrings["en"]["Download"] = "Download";
localizedStrings["en"]["Upload"] = "Upload";
localizedStrings["en"]["This month"] = "This month";
localizedStrings["en"]["Since"] = "Since";
localizedStrings["en"]["started"] = "started";
localizedStrings["en"]["download"] = "download";
localizedStrings["en"]["upload"] = "upload";
localizedStrings["en"]["Last updated"] = "Last updated";
localizedStrings["en"]["Vid&eacute;otron Username"] = "Vid&eacute;otron Username";
localizedStrings["en"]["Bandwidth limit"] = "Bandwidth limit";
localizedStrings["en"]["Total bandwidth limit"] = "Total bandwidth limit";
localizedStrings["en"]["Widget interface"] = "Widget interface";
localizedStrings["en"]["Normal"] = "Normal";
localizedStrings["en"]["Minimal"] = "Minimal";
localizedStrings["en"]["Download + Upload"] = "Download + Upload";
localizedStrings["en"]["Down + Up"] = "Down + Up";
localizedStrings["en"]["img_suffix"] = "_en"; // background{0}.png and background-small{0}.png
localizedStrings["en"]["this_month_percentage_1_pos_total"] = "231px";
localizedStrings["en"]["this_month_percentage_1_small_pos_total"] = "57px";
localizedStrings["en"]["this_month_percentage_1_pos_diff"] = "280px";
localizedStrings["en"]["this_month_percentage_1_small_pos_diff"] = "61px";
localizedStrings["en"]["this_month_percentage_2_pos_diff"] = "294px";
localizedStrings["en"]["this_month_percentage_2_small_pos_diff"] = "77px";
localizedStrings["en"]["Done"] = "Done";
localizedStrings["en"]["Language"] = "Language";
localizedStrings["en"]["Invalid username."] = "<br/><br/>Invalid username.<br/><br/>The username you enter must look like VLXXXXXX, where X are all letters.";
localizedStrings["en"]["Type of access"] = "Type of access";
localizedStrings["en"]["Basic"] = "Basic";
localizedStrings["en"]["High-Speed"] = "High-Speed";
localizedStrings["en"]["Extreme High-Speed"] = "Extreme High-Speed";
localizedStrings["en"]["Extreme Plus High-Speed"] = "Extreme Plus High-Speed";
localizedStrings["en"]["Ultimate Speed 30"] = "Ultimate Speed 30";
localizedStrings["en"]["Ultimate Speed 50"] = "Ultimate Speed 50";
localizedStrings["en"]["Business - Ultimate Speed 30"] = "Business - Ultimate Speed 30";
localizedStrings["en"]["Business - Ultimate Speed 50"] = "Business - Ultimate Speed 50";
localizedStrings["en"]["Download more stuff!"] = "Download more stuff!";
localizedStrings["en"]["Slow down buddy!"] = "Slow down buddy!";
localizedStrings["en"]["Surplus available"] = "Surplus available";
localizedStrings["en"]["A new version is available."] = 'A new version is available. Get it <a href="#" onclick="widget.openURL(\'http://www.pommepause.com/videotron/\')">here</a>.';
localizedStrings["en"]["New version available"] = '<a href="#" onclick="widget.openURL(\'http://www.pommepause.com/videotron/\')">New version available</a>';
localizedStrings["en"]["GB"] = "GB";
localizedStrings["en"]["Data transfer packages"] = "Extra data transfer packages bought this month";
